examples/orgs.rs
src/lib.rs
src/rep.rs
src/rep.rs.in
src/repositories.rs

Hi! I added support for organization repository listing, in a similar way to how you did user repo listing. I'm more than happy to make any changes you'd like :heart:

Implement organization repository list support

---

Cargo.toml

Build failed because of two versions of syntex in the dependencies. This fixes it.

Update syntex dependency

---

src/rep.rs.in
src/repositories.rs

Hi,
I've added a create method on Repo to allow creation of new repositories as per [https://developer.github.com/v3/repos/#create](https://developer.github.com/v3/repos/#create).
I had to add a RepoOptions struct and accompanying Builder.
I've tried to keep everything as similar as possible to other code in rep.rs.in so hopefully there won't be too many issues with it.
I did have two queries.
1. Was there any reason the private field on `Repo` was commented out as ```private (keyword)```? I've added it back in for the moment.
2. I've added `team_id` on `RepoOptions` as an u32, since there is currently no implementation of teams in the library. Let me know if this is not the best option, happy to change it.
I'm more than happy to change any of this so please do let me know if you have any …

Add Repository Creation Endpoint

---

src/rep.rs.in

Make repo description optional; it's sometimes null from github

---

Cargo.toml

Updates the Hyper dependency to cover both the 0.9 and 0.10 series. (Straddling both avoids the need to make a major bump to this crate.)

Bump Hyper to support 0.10 as well.

---

src/repositories/mod.rs

This is at the cost of RepoEditOptions having a Default instance.

Remove duplicate field definitions in RepoEditOptionsBuilder

---

src/repositories/mod.rs

I noticed my typo in post-merge review. Surprisingly following the documentation actually breaks my test. So instead I'm leaving a notice with my findings.

Document use of POST rather than PATCH in repo edit

---

src/search/mod.rs

Docs say that the method returns `(repo owner name, repo name)`, but the `Vec::reverse` call actually makes it `(repo name, repo owner name)`. This is inconsistent with the usual way GitHub refers to repositories.
This PR removes the erroneous `reverse` call.

Fix the order of IssuesItem::repo_tuple

---

src/issues/mod.rs

A PR with absolutely no body causes errors with decoding, because GitHub sends a null body:
```
pull_request: {
url: https://api.github.com/repos/NixOS/nixpkgs/pulls/34454,
html_url: https://github.com/NixOS/nixpkgs/pull/34454,
diff_url: https://github.com/NixOS/nixpkgs/pull/34454.diff,
patch_url: https://github.com/NixOS/nixpkgs/pull/34454.patch
},
body: null,
closed_by: null
```

Issue: make body an Option

---

src/lib.rs

`Url::path()` returns the path part of the URL without the query string.
Since the page index is stored as a GET parameter, it is important not to omit the query string.

Fix unfold (pagination)

---

src/issues/mod.rs
src/pulls/mod.rs

This implements support for part of the missing bits of the github API for PRs documented at https://developer.github.com/v3/pulls/#labels-assignees-and-milestones as being shared with the issues API.
Note that this contains an incompatible change to IssueLabels::new().
-----
I want this for dbaron/wgmeeting-github-ircbot#26.
So far I've tested that the code I want to use it for compiles, but I haven't actually tested that anything works yet.  Before I do that, I'd like to know your reaction to it.  Is this the right approach?  What should happen with the incompatible change?
(I could also go ahead and implement the other missing pieces as well if you think that's appropriate, although I wouldn't have an immediate way to test them.)

Add PullRequest::labels(), and make IssueLabels support being for an issue or a PR

---

src/lib.rs

As of 0.3.2 hubcaps exports an error-chain built Result type

Drop commented Result type alias

---

src/pulls/mod.rs
src/review_comments/mod.rs

Got this working much quicker than I thought. Does this look ok?
Note that this only implements [Review Comment creation](https://developer.github.com/v3/pulls/comments/#create-a-comment), not review creation. However, review comments don't depend on there being a Review first.
Closes #141

Allow to create review comments

---

examples/releases.rs
src/releases/mod.rs

closes #51 and adds more doc comments and a `releases` example

Methods to get latest release and release by tag name

---

src/users/mod.rs

Deserialization fails when the authenticated user doesn't have them set. Unlike the rest of the fields, the `blog` field seems to be an empty string when not set by the user.

Make nullable AuthenticatedUser fields optional

---

src/issues/mod.rs

The data within is not particularly useful, but the `Option` lets us know if the issue is actually an issue or a pull request.

Add `pull_request` field to `Issue` struct

---

Cargo.toml
examples/content.rs
src/content/mod.rs
src/lib.rs

A new version hasn't been published with the last PR that added support to the contents API (#150), so this breaking change should be acceptable:
- Handles paths with spaces and other special characters.
- Handles decoding the file contents upon deserialization.
- Handles the case where we don't know what type of item will be returned using an enum variant. (Is it a file, symlink, or a submodule?)
- Returns a stream of directory items instead of a `Future<Vec<DirectoryItem>>`. We can use `.collect()` if the latter is needed.

Improve contents interface

---

.travis.yml

we had to turn of nightly builds because hyper wasn't compiling. that's fixed now
Closes: #xxx

hypers dependency is fixed. re-enable nightly builds

---

src/lib.rs

Use 9 minutes for the life to give some buffer for clock drift between
our clock and GitHub's. The absolute max is 10 minutes.
Running with these timeouts in production.
None.

Use 9 minute timeout for JWT tokens

---

examples/teams.rs
src/teams/mod.rs

- Create / update / delete teams
- List / add / remove / update team members
I ran the teams example.
Support for creating, updating, deleting teams, plus listing, adding, removing, deleting team members.

Teams: create/update/edit teams + members

---

examples/pulls.rs
src/lib.rs
src/pulls/mod.rs
src/review_requests/mod.rs

Including reading, writing, and deleting for users and teams.
CRUD on Review requests.
I wrote an example, and also modified it to create and delete a review request on a PR: https://github.com/NixOS/nixpkgs/pull/51587#event-2052679040 but removed that part, since it requires write access to the repo so it is unlikely anyone running the examples will have it succeed.
Support for the review request API.

Support Pull Review Requests

---

CHANGELOG.md
Cargo.toml
src/lib.rs

Optional support for using `rustls` via `hyper-rustls` instead of `native-tls` via `hyper-tls`.
It builds.
I added a stub CHANGELOG message.

Optional support for rustls

---

src/lib.rs

`unfold` actually picks the last item from the next page as first item.
```rust
let mut opts = RepoListOptions::builder();
opts.sort(Sort::FullName);
let list = rt.block_on(github.repos().list(&opts.build()))?;
opts.per_page(2);
let iter = rt.block_on(github.repos().iter(&opts.build()).collect())?;
for (e1, e2) in list.iter().zip(iter.iter()) {
println!("{}  {}", e1.name, e2.name);
assert_eq!(e1.name, e2.name);
}
```

`unfold` returns wrong results for next page requests

---

tests/testkit.rs

Fixes a deprecation warning that is new to Rust 1.34: https://doc.rust-lang.org/std/sync/atomic/constant.ATOMIC_USIZE_INIT.html
```
cargo test
```
N/A

Fix deprecation warning in test

---

src/pulls.rs

This field appears to always exists in pull requests and is pretty useful.
Is adding a new field to a struct considered a breaking change? If so, it's going to be hard to fix missing fields.

Add 'merged' field to pull request

---

src/content.rs

This is the same as #204, but has no merge conflicts.

Handle newlines in base64 encoded content

---

examples/collaborators.rs
src/collaborators.rs
src/lib.rs
src/repositories.rs

Dusted off https://github.com/softprops/hubcaps/pull/30 to enable collaborator support.
Ran the example against a test organisation.
The addition of collaborators support

Add support for collaborators

---

src/branches.rs
src/lib.rs

Updated branch protection support to work with current (and preview) protection API
Tested locally on own repos.
That `dismissal_restrictions` are now optional when defining `RequiredPullRequestReviews` and that `required_approving_review_count` may now be specified.

Update protections support to match current API

---

examples/repo_commits.rs
src/lib.rs
src/repo_commits.rs
src/repositories.rs

https://developer.github.com/v3/repos/commits/
1. list commits
2. get a single commit
Has a couple todos, called out with github comments. What do you think from here?
```
cargo run --example repo_commits
cargo test
```
I also `cargo fmt`'d my added changes, and didn't add unrelated reformats.
nothing, I think :)

repositories: support listing commits

---

examples/invitations.rs
src/lib.rs
src/membership.rs
src/organizations.rs

A very small slice of this API set: https://developer.github.com/v3/orgs/members/#list-pending-organization-invitations
I ran the new example against an org with about 100 invitations.
None.

Add trivial support for listing organization invitations

---

src/issues.rs

This fixes errors removing labels with spaces in them that are described
in dbaron/wgmeeting-github-ircbot#40.
I implemented escaping of the label using `percent_encode` in roughly the same way as the existing use of `percent_encode` in `content.rs`, although using a different escaping setting (which I suspect may be important for labels with a "/" in them, although I didn't test that case).
I compiled https://github.com/dbaron/wgmeeting-github-ircbot/ with a modified version of hubcaps (although applying this patch to the 0.5 release, since I didn't want to figure out the changes needed to upgrade my code to hubcaps master), and ran the test version to successfully remove the label in dbaron/wgmeeting-github-ircbot#40, which had previously failed with the failure described in …

Percent-encode label in IssueLabels::remove().

---

Cargo.toml
src/content.rs
src/issues.rs
src/lib.rs

no-op dependency updates except for `percent-encoding`
`DEFAULT_ENCODE_SET` is no longer available and was replaced in [`url#src/parser.rs`](https://github.com/servo/rust-url/blame/7f1bd6ce1c2fde599a757302a843a60e714c5f72/src/parser.rs#L1122)
with the internal constant `PATH`.
closes: #224 #220 #231 #240

Update deps: base64, dirs, hyperx & percent-encoding

---

src/labels.rs

Labels have a description field. This adds it.
Labels now can create and modify the description field.

add a description to labels

---

src/statuses.rs

GitHub commit statuses have an optional target_url now.
Ran it in production :)
Statuses.target_url is optional now.

Statuses.target_url: optional

---

src/statuses.rs

Related to https://github.com/softprops/hubcaps/pull/249.
`created_at` and `updated_at` are now optional.
Had @grahamc run it in prod.
`Statuses.updated_at` and `Statuses.created_at` are now optional.

Statuses.{created,updated}_at: optional

---

Cargo.toml
src/content.rs

Signed-off-by: Jess Frazelle <jess@oxide.computer>
Added create and update methods for contents, happy to change any of the naming.
using it on a project
You can now create and update file contents.

contents: add create and update methods

---

src/labels.rs

Add optional description field to labels.
using it on a project
labels can now have a description

labels: add description

---

Cargo.toml
examples/branches.rs
examples/conditional_requests.rs
examples/content.rs
examples/forks.rs
examples/invitations.rs
examples/issues.rs
examples/labels.rs
examples/pulls.rs
examples/repos.rs
examples/search_issues.rs
examples/search_repos.rs
examples/stars.rs
examples/teams.rs
examples/watching.rs
src/checks.rs
src/collaborators.rs
src/errors.rs
src/http_cache.rs
src/lib.rs
src/macros.rs
src/stars.rs
tests/conditional_requests.rs

Updates all dependencies, including futures and tokio to support
std::future::Future. I tried to do as few changes as possible so there is very little async await used (not very idiomatic).
BREAKING CHANGE

feat: Update to std futures

---

src/lib.rs

The existing code triggers an error in `jsonwebtoken`; I really don't see how it could ever work.

Use an EncodingKey that actually matches the header.

---

README.md
src/lib.rs

@softprops Thanks for the crate.
This PR is not so important but ... :)
The reason of the PR is that `Credentials::Token` can't be constructed from `&str` how displayed in `README.md`. Which disallows to use _copy&paste workflow_ :smile:

fix README.md example

---

.github/workflows/main.yml
CHANGELOG.md
src/lib.rs

Closes: #269
Fixes an issue reported in #269 when cargo builds with the  httpcache feature is enabled is not compiling.
Get ci to fail -> fix -> observe ci passing

catch httpcache compile error

---

examples/users.rs
src/users.rs

1. Added "fn authenticated_emails" and "UserEmail" struct in "src/users.rs", which fetches from github's "/user/emails"
2. Added a usage example of the new function in "examples/users.rs"
Closes: #277 
1. Since there isn't a generic test suite for api calls, I added it to "examples/users.rs" and eyeballed it.  
1. A new users feature that allows getting "/user/emails"

Auth user emails

---

examples/content.rs
examples/repo_commits.rs
src/content.rs
src/repo_commits.rs

- Allow getting repo contents for files from specific branches
- Allow updating and creating files with binary content by sending bytes
Already using it in our bots and apps.
- Allow getting repo contents for files from specific branches
- Allow updating and creating files with binary content by sending bytes

Modifications to content API

---

src/content.rs

Signed-off-by: Jess Frazelle <jess@oxide.computer>

add delete functionality to contents

---

src/repositories.rs
src/users.rs

I'm using [tera](https://github.com/Keats/tera) and hubcaps for a new project. When trying to pass a `Vec<Repo>` to tera, I got an error that `Repo` didn't implement `Serialize`. 
Since `Deserialize` is already derived for that that type, I'd thought I'd add `Serialize` as well to fix the error. As far as I can see this shouldn't have any negative side-effects.
Using my fork in the new project for now and serializing works as expected.

Add serialize support for repo and user

---

Cargo.toml

I also tuned the `futures` dependency to no longer pull in `futures-executor` crate
Closes: #283 
Closes: #276

Update deps: tokio 1.0, reqwest 0.11 etc.

---

.github/workflows/main.yml
Cargo.toml
src/app.rs
src/content.rs
src/errors.rs
src/jwt.rs
src/lib.rs

JWT support is not always needed. For instance, when writing something
like a GitHub Action, we can rely on PAT authentication and will never
need JWT.
JWT support currently requires `jsonwebtoken` v7, which currently has
several older dependencies (including base64, ring, etc). These
dependencies are updated in `jsonwebtoken` v8 (currently in
beta-status). The v8 branch has been in development for nearly two
years.
This change makes these dependencies optional by adding two new
features: `jwt` and `app`. The `app` feature depends on `jwt` and is
enabled by default to avoid making a backwards-incompatible change. This
allows users to avoid these dependencies by using `default-features =
false`.
This change moves JWT-specific types out of `lib.rs` into a `jwt` module
so they can be …

Make JWT functionality optional with features

---

src/pulls.rs

- Added `PullRequest::iter_files`
- Deprecated `PullRequest::files`
If you're okay with breaking changes, I think simply changing the return type of `PullRequest::files` would be the better solution.
Closes #296
Dogfooding
- Added `PullRequest::iter_files`
- Deprecated `PullRequest::files`

Add PullRequest::iter_files

---

src/checks.rs

I replaced the CheckRun id field from i32 to u64 since CheckRun IDs cannot fit in an `i32` anymore, preventing us from loading recent CheckRuns.
Closes: #289 
I ran cargo test (Though I'm not sure the tests are hitting that code)
BREAKING CHANGE: CheckRun id is now a `u64` instead of a `i32` to accommodate the IDs returned by GitHub.

CheckRun: i32 -> u64 for id
