softprops/hubcaps

- examples/orgs.rs
- src/lib.rs
- src/organizations.rs
- src/rep.rs.in
Both for the currently-authenticated user and a named user. Little bits more of the API! :tada:
> Implement support for listing organizations

- examples/repos.rs
- src/rep.rs.in
> implement listing the languages of a repository

- Cargo.toml
- src/lib.rs
- src/rep.rs.in
[As I happened to notice that you're already aware](https://github.com/servo/rust-url/issues/192), `url` has a new 1.0 version with breaking changes out that the new version of hyper uses. Here's my attempt at upgrading both of those! ✨
> Upgrade hyper and url

- Cargo.toml
Theeeere's a new version of syntex out! 🎉
> Upgrade syntex

- Cargo.toml
- build.rs
- src/deployments.rs
- src/issues.rs
- src/pulls.rs
- src/releases.rs
- src/rep.rs.in
- src/repositories.rs
Fixes #40.
Fixes #41.
Also, fixes some type inference errors that sprouted up because of the upgrade.
What else is there to do at 30,000 feet? 😄
> upgrade serde

- src/comments/mod.rs
There doesn't appear to be an API for adding a comment to an issue, and I wanted one for https://github.com/dbaron/wgmeeting-github-ircbot.  So this adds one, which I used to produce https://github.com/dbaron/wgmeeting-github-ircbot/issues/1#issuecomment-294101464.
This appeared to me at a quick glance to be the logical way to add the API.
> Add API for adding a comment to an issue.

- src/repositories/mod.rs
Before I yak-shave my way into a pointless pit, I'm submitting this PR for early review. Let me know what it's missing to be accepted and/or what I should be doing differently.
> Add repo edit

- src/comments/mod.rs
- src/deployments/mod.rs
- src/errors.rs
- src/gists/mod.rs
- src/hooks/mod.rs
- src/issues/mod.rs
- src/lib.rs
- src/pulls/mod.rs
- src/releases/mod.rs
- src/repositories/mod.rs
- src/search/mod.rs
- src/statuses/mod.rs
- src/teams/mod.rs
A bit of a mixed bag of commits. I'm happy to drop or rework any as you please.
> Shorten builders and Display impls, fix typos, etc

- src/lib.rs
> use serde_json::from_reader over from_str

- src/issues/mod.rs
Adds support for getting an issue by ID directly.
> issues: Support getting an Issue from an IssueRef

- CHANGELOG.md
- examples/labels.rs
- src/issues/mod.rs
- src/pulls/mod.rs
some followup to https://github.com/softprops/hubcaps/pull/121
> fixup labels

- examples/assignees.rs
- examples/branches.rs
- examples/comments.rs
- examples/deployments.rs
- examples/gists.rs
- examples/gists_create.rs
- examples/git.rs
- examples/hooks.rs
- examples/issues.rs
- examples/labels.rs
- examples/orgs.rs
- examples/pulls.rs
- examples/redir.rs
- examples/repos.rs
- examples/search_issues.rs
- examples/search_repos.rs
- examples/stars.rs
- examples/teams.rs
- examples/users.rs
> replace quick_main macro with vanilla mains

- Cargo.toml
- src/branches/mod.rs
- src/comments/mod.rs
- src/deployments/mod.rs
- src/gists/mod.rs
- src/git/mod.rs
- src/hooks/mod.rs
- src/issues/mod.rs
- src/keys/mod.rs
- src/labels/mod.rs
- src/lib.rs
- src/organizations/mod.rs
- src/pull_commits/mod.rs
- src/pulls/mod.rs
- src/releases/mod.rs
- src/repositories/mod.rs
- src/review_comments/mod.rs
- src/search/mod.rs
- src/search/repos.rs
- src/stars/mod.rs
- src/statuses/mod.rs
- src/teams/mod.rs
- src/users/mod.rs
I get increasingly less sure towards the later commits, so feedback and pushback welcome. :)
> Resolve compile & clippy warnings

- examples/traffic.rs
- src/lib.rs
- src/repositories/mod.rs
- src/traffic/mod.rs
> implementation of the traffic api

- examples/notifications.rs
- src/activity/mod.rs
- src/lib.rs
- src/notifications/mod.rs
- list notifications
- mark notifications as read
- get thread / mark as read
- manage thread subscriptions
closes #102
> Implementation of the Notifications API

- src/repositories/mod.rs
- src/users/mod.rs
https://developer.github.com/v3/repos/#list-contributors
> add repository contributors

- examples/conditional_requests.rs
- src/http_cache.rs
- src/lib.rs
Fixes #104
Hey @softprops, here's my initial implementation. It's just an initial proposal and I'm happy to make adjustments as you see fit.  What I'm after is I'd like to have this functionality (in one shape or other) in hubcaps without having to maintain a fork of hubcaps, so any solution that avoids that is good for me.
> Implement conditional requests using ETag

- src/comments/mod.rs
- src/deployments/mod.rs
- src/gists/mod.rs
- src/hooks/mod.rs
- src/issues/mod.rs
- src/notifications/mod.rs
- src/pulls/mod.rs
- src/releases/mod.rs
- src/repositories/mod.rs
- src/search/mod.rs
- src/search/repos.rs
- src/statuses/mod.rs
fixes https://github.com/softprops/hubcaps/issues/166
> reduce builder surface area

- CHANGELOG.md
- Cargo.toml
- examples/conditional_requests.rs
- src/lib.rs
> feature flag httpcache

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
> process improvements

- CHANGELOG.md
- Cargo.toml
- LICENSE
- README.md
> release prep

- README.md
> testing workflow action

- README.md
> testing workflow action2

- .travis.yml
- src/http_cache.rs
- src/lib.rs
- tests/conditional_requests.rs
- tests/testkit/mod.rs
Fixes an issue highlighted in https://github.com/softprops/hubcaps/pull/151#issuecomment-418516391.
Wrote an integration test for this, using the octocat user repos (which the GitHub API docs use).
Perhaps, with this issue fixed, there could be a call-to-action for early adopters to test out the "httpcache" feature.  So we can eventually stabalise it.
> Fix & test conditional requests work with pages

- .travis.yml
- src/lib.rs
Moves header value extraction and url_and_auth future in own methods
Helps: #196 
Builds with default features and with `http_cache` enabled.
> Factor out some bits from Github::request

- examples/fork.rs
- src/repositories.rs
Support for forking repositories
Ran the provided example
Support for forking repositories added
> Add method for forking repos

- examples/forks.rs
- src/repositories.rs
Ability to list/stream forks of a repo
Ran the supplied example
Added ability to list/stream forks of a repo
> Add support for listing forks

- CHANGELOG.md
- src/lib.rs
Provide a custom Debug impl for Credentials which masks security sensitive data
Closes: #241
unit tests
> impl less revealing Debug for Credentials

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- src/lib.rs
> set labels on open issues automatically

- src/lib.rs
Fix pagination with Github Enterprise.
Closes: #246 
Ran the forks example against my company's GHE instance.
* Fixed pagination with Github Enterprise
> Fix paginationon GHE

- src/lib.rs
As @nickelc noticed in the #266 it was unnecessary to change this file.
Thank you @nickelc, and sorry @softprops :disappointed_relieved:
> revert #266

- src/repositories.rs
https://docs.github.com/en/rest/reference/repos#get-all-contributor-commit-activity
> Add repo contributor statistics

- examples/stars.rs
- src/stars.rs
list and iter methods for user stars.
Closes: #175
Manually tested examples file.
title says it all.
> add starred list and iter methods for getting a user's stars

- src/lib.rs
While reading the docs, I noticed a minor typo.
Fixed :)
> Fix a minor docs typo

- CHANGELOG.md
- src/branches.rs
Added "rename branch" support.
Closes: #293
I used the new method in a standalone tool on one of my repositories.
Adding support for "rename branch" (already included in changelog).
> Add rename branch support
